build:nav
wwJavid/paradoks-carbon pull request #2
Opened 2023-05-26 08:26 UTC by Sakneb

2023-05-26 16:01 UTC, wwJavid requested changes
Good job. Please, resolve minor comments.

2023-05-26 19:16 UTC, Sakneb commented on components/brand/brand.module.scss
> +  background-color: $purple;
I wrote it because to see the pixel of it, I will delete it at the end

2023-05-26 19:17 UTC, Sakneb commented on components/header/header.module.scss
> +  gap: 185px;
as I told, I will add "space-between" at the end

2023-05-27 11:33 UTC, Sakneb commented on components/nav/nav.module.scss
> +    gap: 62px;
I changed it to 32px as it was in Figma

2023-05-27 11:36 UTC, Sakneb commented on components/nav/nav.module.scss
> +    font-family: "Helvetica";
Done

2023-05-27 11:36 UTC, Sakneb commented on components/nav/nav.tsx
> +    <div className={styles.nav}>
Done

2023-05-27 14:46 UTC, merged