build:utilities
wwJavid/paradoks-carbon pull request #3
Opened 2023-05-26 08:47 UTC by Sakneb

2023-05-26 16:07 UTC, wwJavid requested changes
Please, resolve the comments.

2023-05-26 16:07 UTC, wwJavid commented on components/utilities/utilities.module.scss
> +
.

2023-05-26 16:07 UTC, wwJavid commented on components/utilities/utilities.module.scss
> +    border-radius: 10%;
why percentage?

2023-05-26 16:07 UTC, wwJavid commented on components/utilities/utilities.tsx
> +      <button className={styles.utilities_button}>Bizə qoşul</button>
Please, take the static words out of the code context: create object describing its usage, and put semantic words as key value pair.

2023-05-26 16:10 UTC, wwJavid commented
> Please, resolve the comments.

Is this current view for you as well or it's related to my machine?

![Screenshot 2023-05-26 at 19 10 07](https://github.com/wwJavid/paradoks-carbon/assets/95052561/248ca068-2080-4246-b440-791d2a148cd6)

2023-05-27 11:39 UTC, Sakneb commented on components/utilities/utilities.tsx
> +      <button className={styles.utilities_button}>Bizə qoşul</button>
I couldn't fix only this

2023-05-27 13:30 UTC, merged